# Platform Info
TARGET_BOARD_PLATFORM := msm8937
TARGET_BOOTLOADER_BOARD_NAME := hannaht

# Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53

# System Images
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true
# BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1572864000

# Boot Animation
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1440

# Hacks
BOARD_CANT_BUILD_RECOVERY_FROM_BOOT_PATCH := true
TARGET_NOT_USE_GZIP_RECOVERY_RAMDISK := true

# Toolbox
TW_USES_TOYBOX := true

LOCAL_PATH := device/phh/hannaht
include $(LOCAL_PATH)/kernel.mk

